[package]
name = "adventofcode2017"
version = "0.1.0"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]

[dependencies]

[[bin]]
name="day1"
path="src/day1/main.rs"

[[bin]]
name="day2"
path="src/day2/main.rs"